//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Laundry_Prov_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header_Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Header_Transaction()
        {
            this.Detail_Transaction = new HashSet<Detail_Transaction>();
        }
    
        public Nullable<int> id_employee { get; set; }
        public Nullable<int> id_customer { get; set; }
        public int id_header_transaction { get; set; }
        public Nullable<System.DateTime> transaction_date_time_header_transaction { get; set; }
        public Nullable<System.DateTime> complete_date_time_header_transaction { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Transaction> Detail_Transaction { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
